name: Pages

on:
  push:
    branches:
      - resume # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use Node.js 19.2.0
        uses: actions/setup-node@v2
        with:
          node-version: "19.2.0"
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies of index
        run: npm install
      - name: Build index
        run: npm run build
      - name: Install Dependencies of notes
        run: npm install
        working-directory: ./notes
      - name: Build notes 
        run: npm run build && mv public ../public/notes
        working-directory: ./notes
      - name: Deploy index
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public